language: java
jdk:
- oraclejdk8
script:
- mvn clean package -DskipTests
deploy:
  provider: releases
  api_key:
    secure: h2AysOwW6MsPCxzrZwNkSxegUaXliCR8MhSa2cPprLdpzn1+1ZOjY8qddwQGNSYD6+Yfz4d5/QR86SUTOsdHESHIyYVNwMSn+0FpEpFPkWjEMqu3RFQhUYUjErgihQIDkjh1DjIKsPT3V7q84K5DfP/rpT8Y2YIISzUSE4ID/c4RovXJV3c5fbpxlx5RcRI1azT7Y6mIWaLXIfz4P9rAtWUfYjKXUVJJQS4D4U0w6zp/kUkm7ZA1NLkUVQDPknlOxmAsw0Y/Sn9myTNP0todQ0h923TuKqF9O5Gb8CKULAS8Sbxqv5KSOuLokIu+ih57dzYNUIEwVC1x7gZUBUuweX9lqDlpZ4QGI+QjoVzhiK608sQ6EXPAIgdC0YoM7g2s9B6jrbHzbWkSI4VfoAI/Og7fSQps0cKPcZev82dQZPCdJnlHXSDae9OH8AZfn6a1EjzHA9EyKcu92cPLTo6F+EBx886o8gYnT+ixycUtzvlZVCw29wttwrTW9KkICzxKPpV2wqpw2EUbKodmKmegnDX1uZ2BNf8gKIUiuC5U4V90io5HRPr/L8OWgPSuqZTqlciGuO3ZtsS6qFMRvdwCEMa2j4jC7ONALmi2b7snL5SLhCc1Twwkynq3iXdBzsvYRBcK2it9eviW9Cu74Y3uVi7H40mVzI7kNjtQLzEhbI8=
  file: passkeeper-0.0.1-SNAPSHOT.jar
  skip_cleanup: true
  on:
    tags: true
    #repo: tingjan1982/password-keeper
