language: java
jdk:
- oraclejdk8
script:
- mvn clean package -DskipTests
before_deploy:
  - git config --global user.email "tingjan1982@gmail.com"
  - git config --global user.name "Travis CI Auto Tag"
  #- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  #- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - export GIT_TAG=$TRAVIS_BRANCH-snapshot
  - git tag $GIT_TAG -a -f -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$CI_USER_TOKEN@github.com/tingjan1982/password-keeper --tags
deploy:
  provider: releases
  api_key:
    secure: h2AysOwW6MsPCxzrZwNkSxegUaXliCR8MhSa2cPprLdpzn1+1ZOjY8qddwQGNSYD6+Yfz4d5/QR86SUTOsdHESHIyYVNwMSn+0FpEpFPkWjEMqu3RFQhUYUjErgihQIDkjh1DjIKsPT3V7q84K5DfP/rpT8Y2YIISzUSE4ID/c4RovXJV3c5fbpxlx5RcRI1azT7Y6mIWaLXIfz4P9rAtWUfYjKXUVJJQS4D4U0w6zp/kUkm7ZA1NLkUVQDPknlOxmAsw0Y/Sn9myTNP0todQ0h923TuKqF9O5Gb8CKULAS8Sbxqv5KSOuLokIu+ih57dzYNUIEwVC1x7gZUBUuweX9lqDlpZ4QGI+QjoVzhiK608sQ6EXPAIgdC0YoM7g2s9B6jrbHzbWkSI4VfoAI/Og7fSQps0cKPcZev82dQZPCdJnlHXSDae9OH8AZfn6a1EjzHA9EyKcu92cPLTo6F+EBx886o8gYnT+ixycUtzvlZVCw29wttwrTW9KkICzxKPpV2wqpw2EUbKodmKmegnDX1uZ2BNf8gKIUiuC5U4V90io5HRPr/L8OWgPSuqZTqlciGuO3ZtsS6qFMRvdwCEMa2j4jC7ONALmi2b7snL5SLhCc1Twwkynq3iXdBzsvYRBcK2it9eviW9Cu74Y3uVi7H40mVzI7kNjtQLzEhbI8=
  file: "${TRAVIS_BUILD_DIR}/target/passkeeper-0.0.1-SNAPSHOT.jar" 
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
    #repo: tingjan1982/password-keeper

branches:
  except:
    - /^*-[0-9]/
    - /^*-snapshot/

# Reference
# travis CLI installation issues: https://github.com/travis-ci/travis.rb/issues/391
# Setup GitHub API token for travis CI usage: https://docs.travis-ci.com/user/private-dependencies/#API-Token